# Homework 3


Imagine you're a tech journalist at a major publication. Your editor has just greenlit your next big feature: a compelling deep-dive into OpenAI and Nvidia — two titans in the artificial intelligence space that have shaped the AI boom in dramatically different ways.

On one hand, OpenAI is at the forefront of generative AI and large language models, capturing public imagination with ChatGPT and partnerships with Microsoft. On the other hand, Nvidia powers the hardware backbone of this revolution, producing the GPUs that fuel AI training at scale — and recently became one of the most valuable companies in the world.

Beyond their core innovations, these companies also differ in how they engage with the public. Who is more influential on social media? Which brand has better engagement? Who reaches a broader audience through their content?

In this assignment, you will:

- Collect real Twitter data using the itom6219 package
- Analyze and compare the social presence, content strategy, engagement metrics, and popularity of OpenAI and Nvidia
- Apply techniques like TF-IDF vectorization, topic modeling, and regression analysis
- Draw data-driven conclusions on how these two companies communicate and influence in the digital space



## Step 1: Install ITOM6219 Package.
**You will need to install the itom6219 package to collect Twitter data.**

In [1]:
# Run this cell first, then restart the runtime before continuing
!pip3 install --upgrade git+https://github.com/tantantan12/itom6219.git
!pip3 install pingouin

  Cloning https://github.com/tantantan12/itom6219.git to /tmp/pip-req-build-md6mp412
  Running command git clone --filter=blob:none --quiet https://github.com/tantantan12/itom6219.git /tmp/pip-req-build-md6mp412
  Resolved https://github.com/tantantan12/itom6219.git to commit c2ba75c8a6d468dc3040f71c1b2c78c2fe953bc6
  Preparing metadata (setup.py) ... done


## Step 2: Imports
**Run this cell after restarting the runtime.**

In [2]:
# Core data packages
import os
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix

# Visualization
import plotly.express as px

# NLP & machine learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF

# Statistics
import pingouin as pg

# Twitter data collection
from google.colab import userdata
os.environ['BEARER_TOKEN'] = userdata.get('BEARER_TOKEN')
from itom6219 import user_info, user_tweets, user_tweets_all

## Step 3: Account Summary Comparison

You will need to collect Twitter account data and analyze the Twitter account data. This could be done by using the user_info function.

- Write down your code to collect information about the Twitter account of nvidia by using function user_info from the package of itom6219.
- Print account information of OpenAI (save as user1) and nvidia (save as user2).
- What are the data types of user1 and user2?
- Print the column names of user1.
- print the followers_count for user1(OpenAI).
- print the followers_count for user2(nvidia).
- Generate a boolean variable OpenAI_greater_than_nvidia, which takes the value of True if OpenAI has more followers and False otherwise.
- retrieve the user ids of OpenAI and nvidia. It is stored in the column of "id".

*Complete the above requirements using Python.*

In [3]:
# make sure you run the above block of code to install the user package itom6219.
import os
from google.colab import userdata
os.environ["BEARER_TOKEN"] = userdata.get('BEARER_TOKEN')

from itom6219 import user_info, user_tweets, user_tweets_all
# 💡 Hint (3a): See class notebook Section 3.1 "Identifying Social Media Accounts"

# (3a) Collect Twitter account info for OpenAI and Nvidia
user1 = user_info(["OpenAI"])
user2 = user_info(["nvidia"])

In [4]:
# (3b) Print account information of OpenAI and Nvidia
# 💡 Hint: Use the print() function – see class notebook Section 1.1.2
print(user1)
print(user2)

     name          id                                        description  \
0  OpenAI  4398626122  OpenAI’s mission is to ensure that artificial ...   

   verified                created_at username  \
0      True  2015-12-06T22:51:08.000Z   OpenAI   

   public_metrics.followers_count  public_metrics.following_count  \
0                         4700638                               4   

   public_metrics.tweet_count  public_metrics.listed_count  \
0                        1727                        28353   

   public_metrics.like_count  public_metrics.media_count  
0                       1811                         529  
     name username  verified                created_at        id  \
0  NVIDIA   nvidia      True  2009-07-30T18:25:14.000Z  61559439   

                                         description  \
0  The official handle for NVIDIA. Blog: https://...   

   public_metrics.followers_count  public_metrics.following_count  \
0                         2466120            

In [5]:
# (3c) What are the data types of user1 and user2?
# 💡 Hint: Use type() – see class notebook Section 1.3 (type(twitterAuthorID) example)
print(type(user1))
print(type(user2))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>


In [6]:
# (3d) Print the column names of user1
# 💡 Hint: Use .columns – see class notebook Section 1.4.3 "Examine the Dataframe"
print(user1.columns)

Index(['name', 'id', 'description', 'verified', 'created_at', 'username',
       'public_metrics.followers_count', 'public_metrics.following_count',
       'public_metrics.tweet_count', 'public_metrics.listed_count',
       'public_metrics.like_count', 'public_metrics.media_count'],
      dtype='object')


In [10]:
print(user2.columns)

Index(['name', 'username', 'verified', 'created_at', 'id', 'description',
       'public_metrics.followers_count', 'public_metrics.following_count',
       'public_metrics.tweet_count', 'public_metrics.listed_count',
       'public_metrics.like_count', 'public_metrics.media_count'],
      dtype='object')


In [9]:
# (3e) Print the followers_count for OpenAI (user1)
# 💡 Hint: Access a column with df['column_name'] – see class notebook Section 1.4.3
print(user1["public_metrics.followers_count"])

0    4700638
Name: public_metrics.followers_count, dtype: int64


In [11]:
# (3f) Print the followers_count for Nvidia (user2)
print(user2["public_metrics.followers_count"])

0    2466120
Name: public_metrics.followers_count, dtype: int64


In [12]:
# (3g) Generate a boolean variable: True if OpenAI has more followers than Nvidia
# 💡 Hint: Use a comparison operator (>) – see class notebook Section 1.5.1
#         Use .values[0] to extract a scalar from a single-row dataframe column
OpenAI_greater_than_nvidia = user1["public_metrics.followers_count"].values[0] > user2["public_metrics.followers_count"].values[0]
print(OpenAI_greater_than_nvidia)

True


In [13]:
# (3h) Retrieve the user IDs of OpenAI and Nvidia (stored in column 'id')
# 💡 Hint: Access column 'id' the same way you accessed 'followers_count' above
print(user1["id"])
print(user2["id"])

0    4398626122
Name: id, dtype: object
0    61559439
Name: id, dtype: object


## Step 4: 10 Tweets Comparison

- Use the function user_tweets from the package itom6219 to retrieve 10 tweets generated by OpenAI and Nvidia. Save the result into "tweets_openAI" and "tweets_nvidia".

- Use function head() to display the first five rows of these two dataframes.

- Use function head(n) to display the irst n rows. Allow n to be 3.

- Display the column names of the dataframes.

- How many rows and columns are in tweets_openAI and tweets_nvidia?

- Summarize tweets_openAI and tweets_nvidia using the function of describe. What's the comparison between average  public_metrics.impression_count and public_metrics.impression_count?

- Display the text of tweet from OpenAI and Nvidia that has the highest public_metrics.bookmark_count and public_metrics.impression_count, and public_metrics.impression_count, respectively.

- Generate a new column by using two existing columns to represent the ratio of likes over impression. Which tweet has the highest like ratio for OpenAI and Nvidia, respectively?

*Complete the above requirements using Python.*

In [14]:
# (4a) Retrieve 10 tweets from OpenAI and Nvidia
# 💡 Hint: See class notebook Section 3.1 "Identifying Social Media Accounts"
tweets_openAI = user_tweets(["OpenAI"], exclude_replies=True, exclude_retweets=True)
tweets_nvidia = user_tweets(["nvidia"], exclude_replies=True, exclude_retweets=True)

In [15]:
# (4b) Display the first 5 rows of each dataframe
# 💡 Hint: Use .head() – see class notebook Section 1.4.3 "Examine the Dataframe"
print(tweets_openAI.head())
print(tweets_nvidia.head())

  in_reply_to_user_id                created_at                   id  \
0          4398626122  2026-03-25T17:20:16.000Z  2036855700132147593   
1          4398626122  2026-03-25T17:20:16.000Z  2036855698617938422   
2                 NaN  2026-03-25T17:20:15.000Z  2036855694906057079   
3                 NaN  2026-03-23T20:47:55.000Z  2036183180219392103   
4                 NaN  2026-03-18T17:06:02.000Z  2034315401438580953   

                                                text      conversation_id  \
0  Listen to the OpenAI Podcast on—\nSpotify\nhtt...  2036855694906057079   
1  More on our approach to the Model Spec: https:...  2036855694906057079   
2  The more AI can do, the more we need to ask wh...  2036855694906057079   
3  It’s now easier to find, reuse, and build on t...  2036183180219392103   
4  Are you up for a challenge? \n\nhttps://t.co/G...  2034315401438580953   

  edit_history_tweet_ids lang  public_metrics.retweet_count  \
0  [2036855700132147593]   en            

In [16]:
# (4c) Display the first 3 rows (n = 3) of each dataframe
n = 3
# 💡 Hint: Pass n as an argument to .head(n) – see class notebook Section 1.4.3
print(tweets_openAI.head(n))
print(tweets_nvidia.head(n))

  in_reply_to_user_id                created_at                   id  \
0          4398626122  2026-03-25T17:20:16.000Z  2036855700132147593   
1          4398626122  2026-03-25T17:20:16.000Z  2036855698617938422   
2                 NaN  2026-03-25T17:20:15.000Z  2036855694906057079   

                                                text      conversation_id  \
0  Listen to the OpenAI Podcast on—\nSpotify\nhtt...  2036855694906057079   
1  More on our approach to the Model Spec: https:...  2036855694906057079   
2  The more AI can do, the more we need to ask wh...  2036855694906057079   

  edit_history_tweet_ids lang  public_metrics.retweet_count  \
0  [2036855700132147593]   en                             9   
1  [2036855698617938422]   en                            18   
2  [2036855694906057079]   en                           117   

   public_metrics.reply_count  public_metrics.like_count  \
0                          19                        123   
1                          24

In [17]:
# (4d) Display the column names of both dataframes
# 💡 Hint: Use .columns  – see class notebook Section 1.4.3
print(tweets_openAI.columns)
print(tweets_nvidia.columns)

Index(['in_reply_to_user_id', 'created_at', 'id', 'text', 'conversation_id',
       'edit_history_tweet_ids', 'lang', 'public_metrics.retweet_count',
       'public_metrics.reply_count', 'public_metrics.like_count',
       'public_metrics.quote_count', 'public_metrics.bookmark_count',
       'public_metrics.impression_count', 'username'],
      dtype='object')
Index(['id', 'lang', 'conversation_id', 'edit_history_tweet_ids', 'text',
       'created_at', 'public_metrics.retweet_count',
       'public_metrics.reply_count', 'public_metrics.like_count',
       'public_metrics.quote_count', 'public_metrics.bookmark_count',
       'public_metrics.impression_count', 'in_reply_to_user_id', 'username'],
      dtype='object')


In [18]:
# (4e) How many rows and columns are in each dataframe?
# 💡 Hint: Use .shape – see class notebook Section 1.4.3 "Examine the Dataframe"
print(tweets_openAI.shape)
print(tweets_nvidia.shape)

(10, 14)
(10, 14)


In [19]:
# (4f) Summarize both dataframes using describe()
# 💡 Hint: Use .describe() – see class notebook Section 1.4.3 (df.describe() on AI_tweets data)
print(tweets_openAI.describe())
print(tweets_nvidia.describe())

       public_metrics.retweet_count  public_metrics.reply_count  \
count                     10.000000                   10.000000   
mean                     224.200000                  275.900000   
std                      250.805281                  251.394091   
min                        9.000000                   14.000000   
25%                       24.750000                   31.500000   
50%                      108.500000                  269.000000   
75%                      378.500000                  431.750000   
max                      707.000000                  669.000000   

       public_metrics.like_count  public_metrics.quote_count  \
count                  10.000000                   10.000000   
mean                 2413.900000                  110.400000   
std                  2483.875039                  140.549873   
min                   100.000000                    2.000000   
25%                   336.250000                    7.500000   
50%         

In [20]:
# (4g) Generate like_ratio = likes / impressions; find tweet with highest like ratio
# 💡 Hint: Create a new column by dividing two existing columns (df['col_a'] / df['col_b'])
#         See class notebook Section 3.5 – df_model['engagement_ratio'] example
tweets_openAI['like_ratio'] = tweets_openAI['public_metrics.like_count'] / tweets_openAI['public_metrics.impression_count']
tweets_nvidia['like_ratio'] = tweets_nvidia['public_metrics.like_count'] / tweets_nvidia['public_metrics.impression_count']

print(tweets_openAI.loc[tweets_openAI['like_ratio'].idxmax()])
print(tweets_nvidia.loc[tweets_nvidia['like_ratio'].idxmax()])

in_reply_to_user_id                                                              NaN
created_at                                                  2026-03-23T20:47:55.000Z
id                                                               2036183180219392103
text                               It’s now easier to find, reuse, and build on t...
conversation_id                                                  2036183180219392103
edit_history_tweet_ids                                         [2036183180219392103]
lang                                                                              en
public_metrics.retweet_count                                                     409
public_metrics.reply_count                                                       449
public_metrics.like_count                                                       4749
public_metrics.quote_count                                                       139
public_metrics.bookmark_count                                    

## Step 5: Large Data Comparison

In the previous step, you were able to collectt 10 tweets from OpenAI. Moving forward, use the tweets_openAI.csv and tweets_nvidia.csv, which contain 1500 tweets each. Due to theAPI rate limit, this data is provided to you; you do not need to collect the data by yourself.

- Twitter (now X) began tracking public_metrics.impression_count only in recent years. As a result, older tweets may have a value of zero for impressions. Check the minimum value of public_metrics.impression_count in your dataset. Filter out tweets with zero impressions from both tweets_openAI and tweets_nvidia. Use the updated data (with only non-zero impressions) for all analysis moving forward.

> **Before running the next cell, you need to upload the data files:**
> 1. Download `tweets_nvidia.csv` and `tweets_openAI.csv` from https://github.com/tantantan12/itom6219_2026/tree/main/Week3
> 2. In Google Colab, click the **Files** icon (folder icon) on the left sidebar
> 3. Click the **Upload** button and upload both `tweets_nvidia.csv` and `tweets_openAI.csv`

In [21]:
import pandas as pd

# (5a) Load the provided CSV files (1500 tweets each)
# 💡 Hint: Use pd.read_csv() – see class notebook Section 1.4.3 "Create a dataframe from a csv file"
tweets_openAI = pd.read_csv('tweets_openAI.csv')
tweets_nvidia  = pd.read_csv('tweets_nvidia.csv')

In [22]:
# (5b) Check the minimum value of public_metrics.impression_count in both datasets
# 💡 Hint: Use .min() on a column, e.g. df['col'].min()
print(tweets_openAI['public_metrics.impression_count'].min())
print(tweets_nvidia['public_metrics.impression_count'].min())

0
17694


In [23]:
# (5c) Filter out tweets with zero impressions; use filtered data for all future analysis
# 💡 Hint: Use boolean indexing df[df['col'] > 0] – see class notebook Section 1.5 Conditional Statements
tweets_openAI = tweets_openAI[tweets_openAI['public_metrics.impression_count'] > 0]
tweets_nvidia = tweets_nvidia[tweets_nvidia['public_metrics.impression_count'] > 0]

## Step 6. Data visualization

Modify the code from class exercise to visualize the log(impression+1) and log(like+1) for Twitter and Nvidia over time.

Tip: use pd.to_datetime to convert "created_at" before using it as x-axis.

In [25]:
import plotly.express as px
import numpy as np
import pandas as pd

# (6a) Line plot of log(impression+1) over time for OpenAI and Nvidia
# 💡 Hint: See class notebook Section 3.2 "Data Exploration" – np.log1p() and px.line() example
#         Use pd.to_datetime() to convert 'created_at' first (class notebook Section 3 data cleaning)
#         Add a 'company' label column so you can use color='company' in px.line()

tweets_openAI['datetime'] = pd.to_datetime(tweets_openAI['created_at'])
tweets_nvidia['datetime'] = pd.to_datetime(tweets_nvidia['created_at'])


tweets_openAI['company'] = 'OpenAI'
tweets_nvidia['company'] = 'Nvidia'

df = pd.concat([tweets_openAI, tweets_nvidia])


df['log_impression'] = np.log1p(df['public_metrics.impression_count'])


fig = px.line(df, x='datetime', y='log_impression', color='company',
              title='Log(Impressions+1) Over Time',
              template='plotly_white')

fig.show()

In [26]:
# (6b) Line plot of log(like+1) over time for OpenAI and Nvidia
# 💡 Hint: Same pattern as (6a) – use 'public_metrics.like_count' instead of impression_count
# create log likes
df['log_like'] = np.log1p(df['public_metrics.like_count'])


fig = px.line(df, x='datetime', y='log_like', color='company',
              title='Log(Likes+1) Over Time',
              template='plotly_white')

fig.show()

---
> 📤 **Submit to Canvas — Step 6:** Submit both plots (log impressions over time and log likes over time).
---

## Step 7: Vectorization

Next, we will vectorize the tweet content by generating a document-term matrix with TF-IDF scoress.
- We remove English stopwords.
- max_df=0.8
- min_df=0.02

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

# 💡 Hint: See class notebook Section 3.3 "Vectorization" – the TfidfVectorizer block
#         Here: stop_words='english', max_df=0.8, min_df=0.02
#         Run on tweets_openAI first; repeat for tweets_nvidia in Steps 9 & 10

docs = tweets_openAI['text']

tfidf_vectorizer = TfidfVectorizer(
    stop_words='english',
    max_df=0.8,
    min_df=0.02
)

tfidf = tfidf_vectorizer.fit_transform(docs)

tfidf_df = pd.DataFrame.sparse.from_spmatrix(
    tfidf,
    columns=tfidf_vectorizer.get_feature_names_out()
)

tfidf_df

,4o,ability,access,advanced,ai,amp,announcing,api,app,apps,...,voice,want,way,web,week,windows,work,working,world,writing
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0.406877,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0.291023,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0.40023,0.540485,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0.541607,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,0,0,0,0,0.25731,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
520,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
521,0,0,0,0,0,0,0,0.242589,0,0,...,0,0,0,0,0,0,0,0,0,0
522,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


## Step 8. Topic Discovery
We use non-negative matrix factorization to generate 20 topics.
For each topic, we use the top 3 words to describe the topic.

In [28]:
# Apply NMF
from sklearn.decomposition import NMF

# 💡 Hint: See class notebook Section 3.4 "Topic Modeling" – use n_components=20 here (class used 7)
#         The for-loop to print topic names is also shown there

from sklearn.decomposition import NMF

# create model
nmf_model = NMF(n_components=20, random_state=0)

# fit model
nmf_model.fit(tfidf)

# document-topic matrix
W = nmf_model.fit_transform(tfidf)

# display topics
feature_names = tfidf_vectorizer.get_feature_names_out()
topic_names = []

for topic_index, topic in enumerate(nmf_model.components_):
    top_words = pd.Series(topic, index=feature_names).nlargest(3).index.tolist()
    top_words_string = " ".join(top_words)
    print("Topic #" + str(topic_index) + ": " + top_words_string)
    topic_names.append(top_words_string)

# create topic dataframe
topic_df = pd.DataFrame(W, columns=topic_names)
topic_df

Topic #0: https openai windows
Topic #1: chatgpt available ios
Topic #2: gpt 4o capabilities
Topic #3: ai announcing systems
Topic #4: openai o1 preview
Topic #5: users plus team
Topic #6: models future model
Topic #7: safety sharing security
Topic #8: voice advanced app
Topic #9: research deep work
Topic #10: day https way
Topic #11: new openai features
Topic #12: use canvas work
Topic #13: using custom instructions
Topic #14: soon ll enterprise
Topic #15: eu iceland liechtenstein
Topic #16: ve content sora
Topic #17: o3 mini reasoning
Topic #18: live app 4o
Topic #19: tasks world real


,https openai windows,chatgpt available ios,gpt 4o capabilities,ai announcing systems,openai o1 preview,users plus team,models future model,safety sharing security,voice advanced app,research deep work,day https way,new openai features,use canvas work,using custom instructions,soon ll enterprise,eu iceland liechtenstein,ve content sora,o3 mini reasoning,live app 4o,tasks world real
0,0.049721,0.000000,0.000000,0.000000,0.000000,0.305311,0.005752,0.000000,0.000000,0.000000,0.001150,0.000000,0.000000,0.000000,0.000000,0.005278,0.000000,0.000000,0.000000,0.000000
1,0.039114,0.009519,0.111897,0.000000,0.003182,0.000000,0.000000,0.000000,0.000000,0.031933,0.003897,0.000000,0.000000,0.023954,0.000000,0.000000,0.022409,0.000000,0.009072,0.000000
2,0.028019,0.001114,0.149874,0.001363,0.000000,0.000000,0.000000,0.000000,0.000000,0.013180,0.000000,0.000000,0.000000,0.204244,0.000000,0.000000,0.003164,0.003347,0.006629,0.006877
3,0.038481,0.003885,0.113017,0.000085,0.002582,0.000000,0.000000,0.000000,0.008036,0.014229,0.001913,0.003296,0.000000,0.007307,0.002869,0.000000,0.017881,0.004729,0.008780,0.009813
4,0.052098,0.001866,0.283169,0.000000,0.005230,0.000000,0.000000,0.000000,0.000000,0.011478,0.001524,0.000000,0.000000,0.000000,0.000000,0.000000,0.001347,0.000000,0.003374,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,0.028652,0.000000,0.000000,0.073482,0.000000,0.000000,0.027135,0.000000,0.026596,0.011342,0.000000,0.124888,0.000772,0.017833,0.041129,0.000000,0.003292,0.022107,0.000000,0.000000
520,0.276079,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
521,0.020023,0.053126,0.000000,0.004867,0.074725,0.000000,0.002692,0.000000,0.000000,0.083577,0.000000,0.000000,0.000000,0.000000,0.118001,0.000000,0.124810,0.000000,0.004268,0.000000
522,0.095965,0.000000,0.000000,0.000000,0.000000,0.000000,0.370398,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000


## Step 9 Linear Regression
Model
Construct out outcome variable $log(Likes)=log(Likes+1)$, run the model, and evaluate the model.


In [29]:
# Code for estimating the linear regression model with the outcome being log(Likes)
# 💡 Hint: See class notebook Section 3.5 "Linear Regression"
#         Outcome: log(public_metrics.like_count + 1)  →  np.log1p(...)
#         Predictors: topic columns from W matrix (use pd.DataFrame(W, columns=topic_names))
#         Use pingouin: pg.linear_regression(X, y)

import pingouin as pg

# Step 1: Create model dataframe (topics only)
df_model = topic_df.copy()

# Step 2: Add outcome variable = log(likes + 1)
df_model['log_likes'] = np.log1p(tweets_openAI['public_metrics.like_count'])

# Step 3: Run linear regression
result = pg.linear_regression(
    df_model.drop(columns='log_likes'),   # X = topic columns
    df_model['log_likes']                # Y = outcome
)


In [30]:
# Code for results production
# 💡 Hint: See class notebook Section 3.5 – print the regression results table (.round(3))

result_display = result[['names', 'coef', 'pval']].round(3)

print("Regression Results: Which Topics Drive Likes?\n")
print(result_display)

print("\n How to read this:")
print("- Positive 'coef' = this topic increases likes")
print("- Negative 'coef' = this topic decreases likes")
print("- 'pval' < 0.05 = statistically significant")

Regression Results: Which Topics Drive Likes?

                        names   coef   pval
0                   Intercept  6.997  0.000
1        https openai windows  0.806  0.429
2       chatgpt available ios  9.536  0.000
3         gpt 4o capabilities  1.955  0.012
4       ai announcing systems  1.408  0.369
5           openai o1 preview  2.895  0.000
6             users plus team  2.646  0.009
7         models future model  0.223  0.821
8     safety sharing security -1.234  0.324
9          voice advanced app  0.575  0.536
10         research deep work  0.297  0.737
11              day https way  2.883  0.045
12        new openai features  3.122  0.000
13            use canvas work -0.829  0.633
14  using custom instructions -4.219  0.004
15         soon ll enterprise  1.440  0.337
16   eu iceland liechtenstein  1.239  0.144
17            ve content sora  1.919  0.040
18          o3 mini reasoning  1.449  0.114
19                live app 4o  0.698  0.488
20           tasks world real

Please fill in the text box with your interpretation of the estimates.

### Coefficients Interpretation

```
+--------------------------------------------+
| Topics with positive and significant coefficients (p < 0.05) increase likes, meaning those tweets perform better. Content about new features, product updates, and AI capabilities (like ChatGPT iOS, GPT-4o, and new OpenAI features) tends to get more engagement.

On the other hand, topics like custom instructions have a negative and significant effect, meaning they receive fewer likes.

Most other topics are not statistically significant, so their impact on engagement is unclear. Overall, audiences seem to respond best to exciting updates and new developments.         |
|                                            |
|                                            |
+--------------------------------------------+
```

---
> 📤 **Submit to Canvas — Step 9a:** Submit your coefficients interpretation above.
---

In [31]:
print(result['r2'])

0     0.158418
1     0.158418
2     0.158418
3     0.158418
4     0.158418
5     0.158418
6     0.158418
7     0.158418
8     0.158418
9     0.158418
10    0.158418
11    0.158418
12    0.158418
13    0.158418
14    0.158418
15    0.158418
16    0.158418
17    0.158418
18    0.158418
19    0.158418
20    0.158418
Name: r2, dtype: float64


Please fill in the text box with your interpretation of the R².

### R² Interpretation

```
+----------------------------------------------------------------------+
The R² of 0.158 means that about 15.8% of the variation in likes is explained by the topics in the model. This suggests that while topics do have some influence on engagement, most of the variation in likes is driven by other factors (such as timing, wording, audience behavior, or external events).

If we reduce the number of components to 10 or 5, R² would likely decrease because fewer topics capture less detail about the data. This would make the model simpler but less effective at explaining engagement.                                     |
|                                                                      |
+----------------------------------------------------------------------+
```

---
> 📤 **Submit to Canvas — Step 9b:** Submit your R² interpretation and the comparison across 5/10/20 components.
---

## Step 10: Perform the Same Analysis for Impressions (OpenAI)

Repeat Steps 7–9 using `log(impressions+1)` as the outcome variable instead of likes, still using OpenAI tweets.

```
+-------------------------------------------------------------------------+
| No additional code required — keep the regression output in this cell. |
+-------------------------------------------------------------------------+
```

## Step 11: Topic Modeling and Regression for Nvidia

Repeat Steps 7–9 for both outcomes (likes and impressions) using Nvidia tweets.

```
+-------------------------------------------------------------------------+
| No additional code required — keep the regression output in this cell. |
+-------------------------------------------------------------------------+
```

## Step 12: Summarize Your Findings

Compare OpenAI and Nvidia based on your analysis. What types of content drive engagement for each company? How do they differ?

```
+----------------------------+
| Input your answer here.    |
|                            |
|                            |
+----------------------------+
```

---
> 📤 **Submit to Canvas — Step 12:** Submit your written summary comparing OpenAI and Nvidia.
---